services:
  mcp-server:
    image: mongodb/mongodb-mcp-server:latest
    container_name: mongodb-mcp-server
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    environment:
      # 选择其一：直连 MongoDB
      MDB_MCP_CONNECTION_STRING: "mongodb://your-username:your-password@127.0.0.1:27017/?retryWrites=false&ssl=false&authSource=admin"

      # 或 Atlas Service Account（仅示例，请按需启用）
      # MDB_MCP_API_CLIENT_ID: "your-atlas-service-accounts-client-id"
      # MDB_MCP_API_CLIENT_SECRET: "your-atlas-service-accounts-client-secret"

      MDB_MCP_READ_ONLY: "true"        # 只读，必要时去掉
      MDB_MCP_TRANSPORT: "http"        # 以 HTTP 传输启动
      MDB_MCP_HTTP_HOST: "0.0.0.0"
      MDB_MCP_HTTP_PORT: "3000"
      # MDB_MCP_LOG_PATH: "/home/mcp/.app-logs"
      # 可选：索引检查、日志等
      # MDB_MCP_INDEX_CHECK: "true"
      MDB_MCP_LOGGERS: "mcp,disk,stderr"
      # MDB_MCP_IDLE_TIMEOUT_MS: "600000"
      # MDB_MCP_NOTIFICATION_TIMEOUT_MS: "540000"
    # 如需持久化磁盘日志可挂载目录
    # volumes:
    #   - ./mcp-logs:/home/mcp/.app-logs
    expose:
      - "3000"   # 仅暴露给同一网络内的 nginx
    networks:
      - mongodb-mcp-network

  mcp-nginx:
    image: nginx:stable-perl
    container_name: mongodb-mcp-nginx
    restart: unless-stopped
    depends_on:
      - mcp-server  # 依赖 mcp-server 容器
    ports:
      - "80:80"
      # - "443:443"
    environment:
      BEARER_TOKEN: "your-bearer-token-here"  # 设置Bearer Token用于API认证
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # 将已签发的证书挂载到容器（示例路径请替换为你的证书实际路径）
      # - ./certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      # - ./certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    networks:
      - mongodb-mcp-network

networks:
  mongodb-mcp-network:
    driver: bridge
